// Generated by gencpp from file battery_pkg/Battery.msg
// DO NOT EDIT!


#ifndef BATTERY_PKG_MESSAGE_BATTERY_H
#define BATTERY_PKG_MESSAGE_BATTERY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace battery_pkg
{
template <class ContainerAllocator>
struct Battery_
{
  typedef Battery_<ContainerAllocator> Type;

  Battery_()
    : electricity(0.0)
    , status()  {
    }
  Battery_(const ContainerAllocator& _alloc)
    : electricity(0.0)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef float _electricity_type;
  _electricity_type electricity;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::battery_pkg::Battery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::battery_pkg::Battery_<ContainerAllocator> const> ConstPtr;

}; // struct Battery_

typedef ::battery_pkg::Battery_<std::allocator<void> > Battery;

typedef boost::shared_ptr< ::battery_pkg::Battery > BatteryPtr;
typedef boost::shared_ptr< ::battery_pkg::Battery const> BatteryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::battery_pkg::Battery_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::battery_pkg::Battery_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::battery_pkg::Battery_<ContainerAllocator1> & lhs, const ::battery_pkg::Battery_<ContainerAllocator2> & rhs)
{
  return lhs.electricity == rhs.electricity &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::battery_pkg::Battery_<ContainerAllocator1> & lhs, const ::battery_pkg::Battery_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace battery_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::battery_pkg::Battery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::battery_pkg::Battery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::battery_pkg::Battery_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::battery_pkg::Battery_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::battery_pkg::Battery_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::battery_pkg::Battery_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::battery_pkg::Battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "22b8bb2cbf4d2d5daca78fc9844d7901";
  }

  static const char* value(const ::battery_pkg::Battery_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x22b8bb2cbf4d2d5dULL;
  static const uint64_t static_value2 = 0xaca78fc9844d7901ULL;
};

template<class ContainerAllocator>
struct DataType< ::battery_pkg::Battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "battery_pkg/Battery";
  }

  static const char* value(const ::battery_pkg::Battery_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::battery_pkg::Battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 electricity\n"
"string status\n"
;
  }

  static const char* value(const ::battery_pkg::Battery_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::battery_pkg::Battery_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.electricity);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Battery_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::battery_pkg::Battery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::battery_pkg::Battery_<ContainerAllocator>& v)
  {
    s << indent << "electricity: ";
    Printer<float>::stream(s, indent + "  ", v.electricity);
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BATTERY_PKG_MESSAGE_BATTERY_H
